### PR TITLE
Emails digest includes more content

### PR DESCRIPTION
**Pull request by mjankowski**
Resolves https://github.com/thoughtbot/constable/issues/421

### CODE REVIEW

**Comment by mjankowski** [comment]
Before:

screen shot 2018-09-13 at 9 39 27 am

After:

screen shot 2018-09-13 at 10 08 54 am

I could see making this look better in future improvements, but this seems fine to get the information in there in the first place.

**Comment by paulcsmith** [comment]
I like this, but I also liked how before you could quickly glance at everything that was added and discussed on one screen, even on mobile. What do you think about leaving the current section up top, and adding the full content underneath. Kind of like a table of contents at top with the full content you can jump to if you're interested?

**Comment by mjankowski** [comment]
Like a quick summary of interests and announcements up top - and then a fuller complete digest of all post body content and comments down below? I like that, and will take a crack at that here and update.

**Comment by paulcsmith** [comment]
Yep, exactly!

**Comment by mjankowski** [comment]
screen shot 2018-09-13 at 11 18 53 am

**Comment by paulcsmith** [comment]
Very nice! One tiny suggestion: I think it would look better to put "Posted by <user>" above the announcement body. I think that lines up a bit better. LGTM either way though

**Comment by mjankowski** [comment]
Thing I merged looks like this..

screen shot 2018-09-13 at 12 32 45 pm

...which seems good enough, and can be improved further if wanted.

**Pull request merged**
